### ISSUE TITLE
General Record- search result

### ISSUE THREAD

**Issue by benitopernared530** [Lorauxe/INTROSE#3]
The Day and Time column pertains to the Day and Time of the faculties absence details NOT the details of the class itself ex. Sir Ryan was absent 11/15/2016 so the value that should reflect in the Day and Time Column is T 09:00 - 10:45

**Comment by Lorauxe** [comment]
Made additional tables with it to be able to select the specific day. The old one needs to be checked for all the days while the new one can do it for you already 😀
